name: mobile_games

profile: dbt_sqlite

config-version: 2
version: 0.1

model-paths: ["models"]
test-paths: ["test"]
docs-paths: ["docs"]
snapshot-paths: ["snapshots"]

vars: 
  tracked_specs: ['ram', 'clock_speed', 'int_memory', 'n_cores']

models:
  mobile_games:
    processed:
      +materialized: table
    raw:
      +materialized: table 
